apiVersion: v1
kind: Service
metadata:
  name: agtpython
  labels:
    run: agtpython
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  selector:
    run: agtpython
